    modLoader="javafml"
    loaderVersion="[14,)"
    issueTrackerURL="https://github.com/Agent-Maxwell/Maxwellium-Mod/issues"
    showAsResourcePack=false

    [[mods]]
      modId="maxmod"
      version="1.0.0"
      displayName="Maxwellium Mod"
      updateJSONURL=""
      displayURL=""
      logoFile=""
      credits="god"
      authors="Agent__Maxwell"
      description='''
      Adds funny purple ingot.
      '''

      [[dependencies.examplemod]]
        modId="forge"
        mandatory=true
        versionRange="[14,)"
        ordering="NONE"
        side="BOTH"

      [[dependencies.examplemod]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.12.2]"
        ordering="NONE"
        side="BOTH"